<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.EntityFrameworkCore" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketsAPI.Application\TicketsAPI.Application.csproj" />
    <ProjectReference Include="..\TicketsAPI.Domain\TicketsAPI.Domain.csproj" />
    <ProjectReference Include="..\TicketsAPI.Infrastructure\TicketsAPI.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketsAPI\TicketsAPI.csproj" />
  </ItemGroup>

</Project>
